plugin:
  debug: true

ecosystem:
  enabled: true
  update-interval-ticks: 20

world-intelligence:
  enabled: true
  update-interval-millis: 5000

society:
  enabled: true
  observation-interval-millis: 10000
  villager-analysis-interval-millis: 10000
  social-interval-millis: 10000

behaviour:
  enabled: true
  processing-interval-millis: 1000

  decay:
    half-life-minutes: 30

ai:
  enabled: false

database:
  enabled: false
